apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - axonserver.yaml

patchesStrategicMerge:
  - service.yaml
  - node-selector.yaml
  - mesh.yaml
  - resource-usage-tweaks.yaml
