version: 2
updates:
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /app-backend
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /e2e-tests
    schedule:
      interval: daily
