version: 2
updates:
  - package-ecosystem: npm
    directory: /admin
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: gradle
    directory: /app-backend
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /e2e-tests
    schedule:
      interval: daily
