version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  gradle: circleci/gradle@2.1.0

executors:
  worker:
    docker:
      - image: circleci/python:3.6
    working_directory: /tmp

jobs:
  assemble-executable-jar:
    executor: worker
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                command: ./gradlew assemble
                working_directory: warehouse
      - persist_to_workspace:
          root: warehouse
          paths:
            - build/libs/warehouse-*.jar

  build-and-publish-docker-image:
    executor: worker
    steps:
      - attach_workspace:
          at: /tmp/warehouse
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          path: /tmp/warehouse
          image: sevteen/lobiani-warehouse
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sevteen/lobiani-warehouse
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  deploy:
    jobs:
      - assemble-executable-jar
      - build-and-publish-docker-image
