version: 2.1
orbs:
  gradle: circleci/gradle@2.1.0
  docker: circleci/docker@1.0.1
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          path: warehouse
          image: sevteen/lobiani-warehouse
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sevteen/lobiani-warehouse
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  deploy:
    jobs:
      - gradle/run:
          app_src_directory: warehouse
          command: assemble
      - build-and-push
