version: 2.1

orbs:
  docker: circleci/docker@1.0.1

commands:
  with_gradle_cache:
    steps:
      - run:
          command: >-
            find . -name 'build.gradle.kts' | sort | xargs cat | shasum | awk '{print
            $1}' > /tmp/gradle_cache_seed
          name: Generate Cache Checksum
      - restore_cache:
          key: >-
            gradle-<< parameters.cache_key>>-{{ checksum "/tmp/gradle_cache_seed"
            }}-{{ checksum ".circleci/config.yml" }}
      - steps: << parameters.steps >>
      - save_cache:
          key: >-
            gradle-<< parameters.cache_key>>-{{ checksum "/tmp/gradle_cache_seed"
            }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

jobs:
  assemble-warehouse-executable-jar:
    docker:
      - image: 'cimg/openjdk:14.0'
    steps:
      - checkout
      - with_gradle_cache:
          steps:
            - run:
                command: ./gradlew assemble
                working_directory: warehouse
      - persist_to_workspace:
          root: warehouse
          paths:
            - build/libs/warehouse-*.jar

  build-and-publish-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - attach_workspace:
          at: warehouse
      - docker/build:
          path: warehouse
          image: sevteen/lobiani-warehouse
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sevteen/lobiani-warehouse
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  deploy:
    jobs:
      - assemble-warehouse-executable-jar
      - build-and-publish-docker-image:
          requires:
            - assemble-warehouse-executable-jar
