version: 2.1

orbs:
  docker: circleci/docker@1.0.1
  gradle: circleci/gradle@2.1.0

jobs:
  assemble-warehouse-executable-jar:
    executor: gradle/default
    steps:
      - run: mkdir -p /tmp/workspace
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                command: ./gradlew assemble
                working_directory: warehouse
      - run: cp -r warehouse/build /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - build/libs/warehouse-*.jar

  build-and-publish-docker-image:
    executor: docker/docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          path: /tmp/workspace/
          image: sevteen/lobiani-warehouse
      - docker/push:
          digest-path: /tmp/digest.txt
          image: sevteen/lobiani-warehouse
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  deploy:
    jobs:
      - assemble-warehouse-executable-jar
      - build-and-publish-docker-image:
          requires:
            - assemble-warehouse-executable-jar
