apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-moon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: production
spec:
  destination:
    namespace: moon
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra-config/moon
    repoURL: git@bitbucket.org:sevteen/lobiani
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
