apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - moon.yaml
  - ingress.yaml

patchesStrategicMerge:
  - resource-usage-tweaks.yaml
  - service.yaml
  - browsers.yaml
  - node-selector.yaml
