apiVersion: apps/v1
kind: Deployment
metadata:
  name: moon
  namespace: moon
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: moon
          resources:
            requests:
              cpu: 20m
              memory: 80Mi
            limits:
              cpu: 100m
              memory: 200Mi
        - name: moon-api
          resources:
            requests:
              cpu: 20m
              memory: 80Mi
            limits:
              cpu: 100m
              memory: 200Mi
        - name: selenoid-ui
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
