apiVersion: v1
kind: Namespace
metadata:
  name: lobiani
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lobiani
  name: lobiani-app-backend
  labels:
    app: lobiani-app-backend
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: lobiani-app-backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: lobiani-app-backend
    spec:
      containers:
        - name: lobiani-app-backend
          image: sevteen/lobiani-app-backend@sha256:dd8633a1c7d6bbbced2acd2a0bb69d0de06bbe2c88a87c49846eb939d2c5a32d # Modified by CI at Sun Nov 29 15:41:30 UTC 2020
          imagePullPolicy: Always
          env:
            - name: AXON_AXONSERVER_SERVERS
              value: axonserver.axonserver
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 480Mi
            requests:
              cpu: 100m
              memory: 350Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/inventory-items
      nodeSelector:
        node-type: worker-pool
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lobiani
  name: lobiani-app-frontend
  labels:
    app: lobiani-app-frontend
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: lobiani-app-frontend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: lobiani-app-frontend
    spec:
      containers:
        - name: lobiani-app-frontend
          image: sevteen/lobiani-app-frontend@sha256:929031a3f64a78648bb53c136a3da6995d1e9569909aa589e6630543737b36e9 # Modified by CI at Sat Dec 12 20:09:51 UTC 2020
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 20m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          readinessProbe:
            httpGet:
              port: 80
              path: /
      nodeSelector:
        node-type: worker-pool
---
apiVersion: v1
kind: Service
metadata:
  namespace: lobiani
  name: lobiani-app-backend
  labels:
    app: lobiani-app-backend
spec:
  selector:
    app: lobiani-app-backend
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: lobiani
  name: lobiani-app-frontend
  labels:
    app: lobiani-app-frontend
spec:
  selector:
    app: lobiani-app-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
